apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: local-emulator-config
spec:
  projectID: local-project
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-emulator-credentials
      key: creds
