ktor:
  application:
    modules:
      - com.agnostic.consumer.ApplicationKt.module
  deployment:
    port: 8080

consumer:
  subscription:
    pubSubName: order-pubsub
    topicName: orders
    route: /orders
  telemetry:
    serviceName: consumer
