resources:
  - producer-ktor.yaml
  - consumer-ktor.yaml
  - producer-gin.yaml
  - consumer-gin.yaml
  - producer-springboot.yaml
  - consumer-springboot.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: app.kubernetes.io/component in (producer,consumer)
    path: common-deployment-hardening-patch.yaml
