apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: ${PROVIDER_CONFIG_NAME}
spec:
  projectID: ${GCP_PROJECT_ID}
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: ${GCP_SECRET_NAME}
      key: creds
