ktor:
  application:
    modules:
      - com.agnostic.producer.ApplicationKt.module
  deployment:
    port: 8080

producer:
  dapr:
    pubSubName: order-pubsub
    topicName: orders
  telemetry:
    serviceName: producer
