resources:
  - otel-collector-config.yaml
  - otel-collector.yaml
  - tempo-config.yaml
  - tempo.yaml
  - loki-config.yaml
  - loki.yaml
  - promtail-config.yaml
  - promtail.yaml
  - prometheus-config.yaml
  - prometheus.yaml
  - pushgateway.yaml
  - grafana-datasources.yaml
  - grafana-dashboard-provider.yaml
  - grafana-dashboards.yaml
  - grafana.yaml
