apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: otel-collector
        static_configs:
          - targets: ["otel-collector:9464"]

      - job_name: producer-ktor
        metrics_path: /metrics
        static_configs:
          - targets: ["producer-ktor:8080"]

      - job_name: consumer-ktor
        metrics_path: /metrics
        static_configs:
          - targets: ["consumer-ktor:8080"]

      - job_name: producer-gin
        metrics_path: /metrics
        static_configs:
          - targets: ["producer-gin:8080"]

      - job_name: consumer-gin
        metrics_path: /metrics
        static_configs:
          - targets: ["consumer-gin:8080"]

      - job_name: producer-springboot
        metrics_path: /metrics
        static_configs:
          - targets: ["producer-springboot:8080"]

      - job_name: consumer-springboot
        metrics_path: /metrics
        static_configs:
          - targets: ["consumer-springboot:8080"]

      - job_name: pushgateway
        honor_labels: true
        static_configs:
          - targets: ["pushgateway:9091"]
