apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: otel-collector
        static_configs:
          - targets: ["otel-collector:9464"]

      - job_name: producer
        metrics_path: /metrics
        static_configs:
          - targets: ["producer:8080"]

      - job_name: consumer
        metrics_path: /metrics
        static_configs:
          - targets: ["consumer:8080"]

      - job_name: pushgateway
        honor_labels: true
        static_configs:
          - targets: ["pushgateway:9091"]
